// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "This parameter is necessary for the extension method.", Scope = "member", Target = "~M:Krafted.IntegrationTest.Migration.KraftedDataBase.UseMigration(Microsoft.AspNetCore.Builder.IApplicationBuilder,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "This is a common way to name files that correspond to a generic type. The number after ` correspond to the quantity of generic arguments.", Scope = "type", Target = "~T:Krafted.IntegrationTest.Startup")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1043:Remove 'partial' modifier from type with a single part.", Justification = "The intent is explicitly show that this is a partial class", Scope = "type", Target = "~T:Krafted.IntegrationTest.FooBar.FooControllerTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RCS1198:Avoid unnecessary boxing of value type.", Justification = "The readability", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.FooControllerTest.Delete_ExistentId_SuccessAndCorrectContentTypeAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RCS1198:Avoid unnecessary boxing of value type.", Justification = "The readability", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.FooControllerTest.Put_ExistentId_SuccessAndCorrectContentTypeAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RCS1198:Avoid unnecessary boxing of value type.", Justification = "The readability", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.FooControllerTest.GetById_ExistentId_SuccessAndCorrectContentTypeAsync~System.Threading.Tasks.Task")]