// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "This parameter is necessary for the extension method.", Scope = "member", Target = "~M:Krafted.IntegrationTest.Migration.KraftedDataBase.UseMigration(Microsoft.AspNetCore.Builder.IApplicationBuilder,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1043:Remove 'partial' modifier from type with a single part.", Justification = "The intent is explicitly show that this is a partial class", Scope = "type", Target = "~T:Krafted.IntegrationTest.FooBar.FooControllerTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "RCS1016:Use expression-bodied member.", Justification = "Expression-bodied member no used in constructors", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.Application.FooApplicationService.#ctor(SharedKernel.Domain.IRepositoryAsync{Krafted.IntegrationTest.FooBar.Domain.Foo},SharedKernel.Transactions.IUnitOfWork,SharedKernel.Application.Commands.Result.ICommandResultFactory)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "RCS1016:Use expression-bodied member.", Justification = "Expression-bodied member no used in constructors", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.Application.DeleteFooCommand.#ctor(System.Guid)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RCS1231:Make parameter ref read-only.", Justification = "C# 7.2 feature", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.Domain.Foo.#ctor(System.String,System.DateTime,System.DateTime)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RCS1231:Make parameter ref read-only.", Justification = "C# 7.2 feature", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.Domain.Foo.ChangeSchedule(System.DateTime,System.DateTime)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1175:Unused this parameter.", Justification = "Needed for extension method", Scope = "member", Target = "~M:Krafted.IntegrationTest.Migration.KraftedDataBase.UseMigration(Microsoft.AspNetCore.Builder.IApplicationBuilder,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "RCS1016:Use expression-bodied member.", Justification = "Expression-bodied member no used in constructors", Scope = "member", Target = "~M:Krafted.IntegrationTest.Infrastructure.Sql.Bultin.BultinSqlBuilderTest.#ctor")]