// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "This parameter is necessary for the extension method.", Scope = "member", Target = "~M:Krafted.IntegrationTest.Migration.KraftedDataBase.UseMigration(Microsoft.AspNetCore.Builder.IApplicationBuilder,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "This is a common way to name files that correspond to a generic type. The number after ` correspond to the quantity of generic arguments.", Scope = "type", Target = "~T:Krafted.IntegrationTest.Startup")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1043:Remove 'partial' modifier from type with a single part.", Justification = "The intent is explicitly show that this is a partial class", Scope = "type", Target = "~T:Krafted.IntegrationTest.FooBar.FooControllerTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RCS1198:Avoid unnecessary boxing of value type.", Justification = "The readability", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.FooControllerTest.Delete_ExistentId_SuccessAndCorrectContentTypeAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RCS1198:Avoid unnecessary boxing of value type.", Justification = "The readability", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.FooControllerTest.Put_ExistentId_SuccessAndCorrectContentTypeAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RCS1198:Avoid unnecessary boxing of value type.", Justification = "The readability", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.FooControllerTest.GetById_ExistentId_SuccessAndCorrectContentTypeAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Readability", "RCS1008:Use explicit type instead of 'var' (when the type is not obvious).", Justification = "The type is obvious", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.Controllers.FooController.GetByIdAsync(System.Guid)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Readability", "RCS1008:Use explicit type instead of 'var' (when the type is not obvious).", Justification = "The type is obvious", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.Controllers.FooController.GetAllAsync~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Readability", "RCS1008:Use explicit type instead of 'var' (when the type is not obvious).", Justification = "The type is obvious", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.Controllers.FooController.PostAsync(Krafted.IntegrationTest.FooBar.Application.CreateFooCommand)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Readability", "RCS1008:Use explicit type instead of 'var' (when the type is not obvious).", Justification = "The type is obvious", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.Controllers.FooController.PutAsync(System.Guid,Krafted.IntegrationTest.FooBar.Application.ChangeScheduleFooCommand)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Readability", "RCS1008:Use explicit type instead of 'var' (when the type is not obvious).", Justification = "The type is obvious", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.Controllers.FooController.DeleteAsync(System.Guid)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Readability", "RCS1008:Use explicit type instead of 'var' (when the type is not obvious).", Justification = "The type is obvious", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.Application.FooApplicationService.HandleAsync(Krafted.IntegrationTest.FooBar.Application.ChangeScheduleFooCommand)~System.Threading.Tasks.Task{SharedKernel.Application.Commands.Result.ICommandResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Readability", "RCS1008:Use explicit type instead of 'var' (when the type is not obvious).", Justification = "The type is obvious", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.Application.FooApplicationService.HandleAsync(Krafted.IntegrationTest.FooBar.Application.DeleteFooCommand)~System.Threading.Tasks.Task{SharedKernel.Application.Commands.Result.ICommandResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Readability", "RCS1008:Use explicit type instead of 'var' (when the type is not obvious).", Justification = "The type is obvious", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.Application.FooApplicationService.HandleAsync(Krafted.IntegrationTest.FooBar.Application.CancelFooCommand)~System.Threading.Tasks.Task{SharedKernel.Application.Commands.Result.ICommandResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "RCS1016:Use expression-bodied member.", Justification = "Expression-bodied member no used in constructors", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.Application.FooApplicationService.#ctor(SharedKernel.Domain.IRepositoryAsync{Krafted.IntegrationTest.FooBar.Domain.Foo},SharedKernel.Transactions.IUnitOfWork,SharedKernel.Application.Commands.Result.ICommandResultFactory)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "RCS1016:Use expression-bodied member.", Justification = "Expression-bodied member no used in constructors", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.Application.DeleteFooCommand.#ctor(System.Guid)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RCS1231:Make parameter ref read-only.", Justification = "C# 7.2 feature", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.Domain.Foo.#ctor(System.String,System.DateTime,System.DateTime)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RCS1231:Make parameter ref read-only.", Justification = "C# 7.2 feature", Scope = "member", Target = "~M:Krafted.IntegrationTest.FooBar.Domain.Foo.ChangeSchedule(System.DateTime,System.DateTime)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1175:Unused this parameter.", Justification = "Needed for extension method", Scope = "member", Target = "~M:Krafted.IntegrationTest.Migration.KraftedDataBase.UseMigration(Microsoft.AspNetCore.Builder.IApplicationBuilder,System.String)")]