// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "This query is automatically generated by the BultinSqlBuilder", Scope = "member", Target = "~M:Krafted.Data.SqlServer.SqlBuilder.BultinSqlBuilder`1.GetCommandBuilder(System.Data.StatementType)~System.String")]