apiRules:
  - include:
      uidRegex: ^Krafted\.UnitTests
      type: Type
  - exclude:
      uidRegex: ^System\.Object
      type: Type
  - exclude:
      uidRegex: ^Microsoft\.AspNetCore\.Mvc\.Controller
      type: Type
  - exclude:
      uidRegex: ^System\.Object\.GetHashCode
      type: Member
  - exclude:
      uidRegex: ^Krafted\.UnitTest
      type: Type
  - exclude:
      uidRegex: ^Krafted\.IntegrationTest
      type: Type
  - exclude:
      uidRegex: ^Krafted\.Net\.Network
      type: Type
  - exclude:
      uidRegex: ^Krafted\.ValueObjects\.Br
      type: Type
