// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "Necessary for the extension method", Scope = "member", Target = "~M:Krafted.UnitTest.Infrastructure.Connections.SqlServer.AssertExtension.DoesNotThrow(Xunit.Assert,System.Action)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1175:Unused this parameter.", Justification = "Necessary for the extension method", Scope = "member", Target = "~M:Krafted.UnitTest.Infrastructure.Connections.SqlServer.AssertExtension.DoesNotThrow(Xunit.Assert,System.Action)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1806:Do not ignore method results", Justification = "Just to test", Scope = "member", Target = "~M:Krafted.UnitTest.Infrastructure.Connections.SqlServer.SqlServerConnectionProviderTest.NewInstance_FilledConnectionString_ArgumentExceptionShouldNotBeThrow(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1481:Unused local variables should be removed", Justification = "Just to test", Scope = "member", Target = "~M:Krafted.UnitTest.Infrastructure.Repositories.Dapper.RepositoryTest.Transaction_Call_ShouldBeReceived")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1806:Do not ignore method results", Justification = "Just to test", Scope = "member", Target = "~M:Krafted.UnitTest.Infrastructure.Connections.SqlServer.SqlServerConnectionProviderTest.NewInstance_NotFilledConnectionString_ExceptionShouldBeThrow(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1001:Types that own disposable fields should be disposable", Justification = "Just to test", Scope = "type", Target = "~T:Krafted.UnitTest.Api.ProviderStateApiFactoryTest")]