//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krafted.Guards {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krafted.Guards.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection cannot be empty..
        /// </summary>
        internal static string CollectionCannotBeEmpty {
            get {
                return ResourceManager.GetString("CollectionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection should be empty..
        /// </summary>
        internal static string CollectionShouldBeEmpty {
            get {
                return ResourceManager.GetString("CollectionShouldBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail address: {0}..
        /// </summary>
        internal static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid NIF: {0}..
        /// </summary>
        internal static string InvalidNif {
            get {
                return ResourceManager.GetString("InvalidNif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL: {0}..
        /// </summary>
        internal static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number cannot be greater than {0}..
        /// </summary>
        internal static string NumberCannotBeGreaterThan {
            get {
                return ResourceManager.GetString("NumberCannotBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number cannot be less than {0}..
        /// </summary>
        internal static string NumberCannotBeLessThan {
            get {
                return ResourceManager.GetString("NumberCannotBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number cannot be negative..
        /// </summary>
        internal static string NumberCannotBeNegative {
            get {
                return ResourceManager.GetString("NumberCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number cannot be positive..
        /// </summary>
        internal static string NumberCannotBePositive {
            get {
                return ResourceManager.GetString("NumberCannotBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number cannot be zero..
        /// </summary>
        internal static string NumberCannotBeZero {
            get {
                return ResourceManager.GetString("NumberCannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be false..
        /// </summary>
        internal static string ParameterCannotBeFalse {
            get {
                return ResourceManager.GetString("ParameterCannotBeFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be null..
        /// </summary>
        internal static string ParameterCannotBeNull {
            get {
                return ResourceManager.GetString("ParameterCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be null, empty or consists exclusively of white-space characters..
        /// </summary>
        internal static string ParameterCannotBeNullEmptyOrWhiteSpace {
            get {
                return ResourceManager.GetString("ParameterCannotBeNullEmptyOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be null or empty..
        /// </summary>
        internal static string ParameterCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ParameterCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be true..
        /// </summary>
        internal static string ParameterCannotBeTrue {
            get {
                return ResourceManager.GetString("ParameterCannotBeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter matches the specified regular expression..
        /// </summary>
        internal static string ParameterMatchesRegEx {
            get {
                return ResourceManager.GetString("ParameterMatchesRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least {1} characters..
        /// </summary>
        internal static string ParameterMustBeAtLeastLength {
            get {
                return ResourceManager.GetString("ParameterMustBeAtLeastLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at most {1} characters..
        /// </summary>
        internal static string ParameterMustBeAtMostLength {
            get {
                return ResourceManager.GetString("ParameterMustBeAtMostLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be length {1}..
        /// </summary>
        internal static string ParameterMustBeExactLength {
            get {
                return ResourceManager.GetString("ParameterMustBeExactLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least {1} character, and at most {2} characters..
        /// </summary>
        internal static string ParameterMustBeInsideRangeLength {
            get {
                return ResourceManager.GetString("ParameterMustBeInsideRangeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter not matches the specified regular expression..
        /// </summary>
        internal static string ParameterNotMatchesRegEx {
            get {
                return ResourceManager.GetString("ParameterNotMatchesRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicate cannot be false..
        /// </summary>
        internal static string PredicateCannotBeFalse {
            get {
                return ResourceManager.GetString("PredicateCannotBeFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicate cannot be true..
        /// </summary>
        internal static string PredicateCannotBeTrue {
            get {
                return ResourceManager.GetString("PredicateCannotBeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not exists in the {1}..
        /// </summary>
        internal static string ValueNotExistsIn {
            get {
                return ResourceManager.GetString("ValueNotExistsIn", resourceCulture);
            }
        }
    }
}
