//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krafted.ValueObjects {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krafted.ValueObjects.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da conta deve ter no máximo {0} caracteres..
        /// </summary>
        internal static string AccountNameMustBeAtMostCharacters {
            get {
                return ResourceManager.GetString("AccountNameMustBeAtMostCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O saldo deve ser positivo..
        /// </summary>
        internal static string BalanceMustBePositive {
            get {
                return ResourceManager.GetString("BalanceMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria deve ter no máximo {0} caracteres..
        /// </summary>
        internal static string CategoryMustBeAtMostCharacters {
            get {
                return ResourceManager.GetString("CategoryMustBeAtMostCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição deve ter no máximo {0} caracteres..
        /// </summary>
        internal static string DescriptionMustBeAtMostCharacters {
            get {
                return ResourceManager.GetString("DescriptionMustBeAtMostCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado já está em uso..
        /// </summary>
        internal static string EmailHasAlreadyBeenUsed {
            get {
                return ResourceManager.GetString("EmailHasAlreadyBeenUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail deve ter no máximo {0} caracteres..
        /// </summary>
        internal static string EmailMustBeAtMostCharacters {
            get {
                return ResourceManager.GetString("EmailMustBeAtMostCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a conta..
        /// </summary>
        internal static string EnterAccount {
            get {
                return ResourceManager.GetString("EnterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a categoria..
        /// </summary>
        internal static string EnterCategory {
            get {
                return ResourceManager.GetString("EnterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a data..
        /// </summary>
        internal static string EnterDate {
            get {
                return ResourceManager.GetString("EnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data informada é inválida..
        /// </summary>
        internal static string EnterDateInvalid {
            get {
                return ResourceManager.GetString("EnterDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a descrição..
        /// </summary>
        internal static string EnterDescription {
            get {
                return ResourceManager.GetString("EnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o e-mail..
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o grupo..
        /// </summary>
        internal static string EnterGroup {
            get {
                return ResourceManager.GetString("EnterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a senha..
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail inválido..
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mês inválido..
        /// </summary>
        internal static string InvalidMonth {
            get {
                return ResourceManager.GetString("InvalidMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano inválido..
        /// </summary>
        internal static string InvalidYear {
            get {
                return ResourceManager.GetString("InvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter no mínimo {0} caracteres..
        /// </summary>
        internal static string PasswordMustBeAtLeastCharacters {
            get {
                return ResourceManager.GetString("PasswordMustBeAtLeastCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter no máximo {0} caracteres..
        /// </summary>
        internal static string PasswordMustBeAtMostCharacters {
            get {
                return ResourceManager.GetString("PasswordMustBeAtMostCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas não coincidem..
        /// </summary>
        internal static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha inválidos..
        /// </summary>
        internal static string UserOrPasswordInvalid {
            get {
                return ResourceManager.GetString("UserOrPasswordInvalid", resourceCulture);
            }
        }
    }
}
